project:
  type: website
  output-dir: docs

website:
  title: Jeffrey S. Racine's Personal Blog
  site-url: https://jeffreyracine.github.io/blog
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JeffreyRacine
      - icon: rss
        href: index.xml

listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  feed: true

format:
  html:
    theme: cosmo
    css: styles.css



