project:
  type: website
  output-dir: docs
  post-render:
    - scripts/style-rss.sh

website:
  title: Jeffrey S. Racine's Personal Blog
  site-url: https://jeffreyracine.github.io/blog/
  repo-url: https://github.com/JeffreyRacine/blog
  repo-actions: [source]
  navbar:
    right:
      - about.qmd
      - text: Research
        href: https://jeffreyracine.github.io/research/
      - text: Gallery
        href: https://jeffreyracine.github.io/gallery/
      - text: CV
        href: https://jeffreyracine.github.io/vitae/
      - icon: github
        href: https://github.com/JeffreyRacine/blog
        aria-label: Blog source on GitHub
      - icon: rss
        href: index.xml
        aria-label: RSS feed

format:
  html:
    theme: cosmo
    css: styles.css
    link-external-newwindow: true
