---
title: Lighting up Five Cats
author: Jeffrey S. Racine
date: 2023-11-18
draft: false
feed: true
---

Well, when life gives you lemons, you don't have make lemonade?

This is to document my recent experiences with the five cats, or more accurately Ethernet Category Five (Cat 5) cables and related things.

Some background is in order. Over a decade ago we bundled many home utilities (cellular phone, land line, internet, television) into a single package with a single provider (100 MB download speeds, 20 MB upload), Bell. But my workflow involves shuffling large amounts of data back and forth from home to the university which taxed the system, and although Bell kept saying we would see fiber optic line in our neighborhood for years, it never materialized. Then a competitor (Cogeco) provided much faster service to our neighborhood via coaxial cabling (1 GB download, 30 MB upload) and I switched, and was fairly happy. But we had line issues over the years (corrosion) though they were always resolved. A few years ago Bell finally brought fiber to our neighborhood, but I was not compelled to switch, and Cogeco always matched the Bell prices (which were less expensive) so that kept me happy. However, in early October the speeds dropped (upload in particular) and the service became unacceptable, as with 15 MB upload speeds using rsync to synchronize home and work computers was taking so long it was interfering with my workflow. So naturally I contacted Cogego, and a total shitshow erupted with 5 visits from technicians who never came with the right equipment, or were not given any instructions or details about previous visits, and after the 5th visit where the tech said "you have a signal problem" (diagnosed by the first tech after his second visit on the same day as he arrived with a broken signal meter) I started thinking about switching.

But fate was being finicky. The first Cogeco rep said they offer newer wifi (mesh Wi-Fi 6) and on the 3rd visit they switched out our equipment (the old equipment was a router and two *wired* extenders that serviced the entire house fairly well). They installed the new router and two mesh *pods*, and then the show began. We had much worse network coverage throughout the house, and they recommended getting additional pods which became 6 in total. But still things were not good, and I started digging around for information on the system (Sagemcom Fast 3896 and Plume Superpods) and realized that I might need to hard wire the pods to the router. So, to experiment I bought two 100 foot Cat 6 Ethernet 
and started experiment. But the happy intervention of fate was reading that to get the best speeds from my computer I should connect my computer directly to the router, if possible. So I did, and the speeds were amazing (1 GB download, but sadly still 15 MB upload due to the ongling signal issue). I also learned that these routers have 1 10 GB/s port, the rest 1 GB/s. Cogeco's shitshow turned into a learning experience in many ways. I discovered a utility called *networkQuality* that measures realized network speed, and was getting around 800 MB/s down and 15 MB/s up.

Here is one happy unforseend outcome. After running *networkQuality* at home, I tried it at work, and was surprised to say the least. My office has 1 GB/s Ethernet, but I was getting 80 up and down??? I contacted UTS and they said to try a different patch cord, which I did, and it was Cat 5 that has a maximum speed of 100 MB/s. I tried a newer patch and voila! 1 GB/s up and down. So, I had been living for years with 1/10 of the speed I was supposed to be getting, who knew? Thanks Cogeco!

Then I realized I needed to cut the cord and switch as they were totally unresponsive. Bell recently installed fiber in our nweighborhood, and I called and found out I could get 3 GB up and down for the same price I was paying Cogeco for 1 GB up and 30 MB down. Done. After a bit of a frustrating experience with Bell, I ordered their service and waited for the install (yesterday). I was nervous as I didn't know whether they might have to dig up our front yard or not, and they said the tech would arrive between 8-10 AM and that it would take between 4-6 hours (it took 6+ with my help). But the tech was a super understanding and very competent professional, and we moved the new router to the middle of the house on the main floor (the old was at the side of the house in the basement where the cable entered the house), installed Ethernet cables to my computer and a pod on the far side of the house, and though the tech had 6 pods we kepd only 4 and he felt this was overkill (he was right). When we first fired up my computer to test the speed, it was only 1 GB/s and I suspected a cable issue, but he had not plugged the cable into the 10 GB port and once he did we got 3.1 GB up and down, and he was positively giddy and took a screenshot declaring it was the fastest he has ever seen (typically maxes out around 2.5 he said). I had some issues with interference, and the Bell Wi-Fi app won't be available to me for a week as this is a new install so I can't yet optimize the system, but all is good. And, as an aside, the Bell Fibe TV is much better than Cogeco's, and the Bell Fibe app is amazing (I can watch TV on my phone or tablet anywhere in the house, and it is super fast and responsive). So better internet, better TV, no increase in price and the bery latest Wi-Fi 6E equipment, so color me happy).