---
title: Migrating from R blogdown to Quarto blogging
author: Jeffrey S. Racine
date: 2023-08-11
draft: false
feed: true
---

Ahh, the joys and sorrows of technological progress! 

Some background is likely in order (along with an apology for neglecting this blog for so long). In 2018 I discovered R blogdown, which struck me as a stable and forward-looking platform for creating and maintaining a free and open source blog. It also turned out that using RStudio and R blogdown for building websites was a very straightforward matter.^[In fact, some features that streamlined creating new posts using RStudio are in fact currently missing from my newly migrated Quarto blogging framework, though since Quarto Markdown is an evolution of R Markdown undertaken by the same team of developers, one might expect missing features to re-appear.] However, the R blogdown framework came with its own set of issues, and having to actively modify and maintain a theme in order to accomplish certain tasks created conditions for its eventual neglect (a *Hugo* theme for the curious). In addition, I was using the free hosting platform netlify and leveraging its ability to pull updated code from a GitHub repo to automatically rebuild the blog. But, not long after adopting this approach, this framework became unmaintainable, i.e., not worth the effort. In particular, the cumulative effect of netlify issuing security warnings about the Hugo theme, issues with GitHub's security features, GitHub moving away from passwords, etc., all seemed to conspire against continued use of this adopted framework. In short, I was unwilling to invest the time to debug and maintain this framework, hence it lapsed and became YANB (*yet another neglected blog*) which explains the large gap between certain posts (and my offer of an apology).

But with my recent experiences using Quarto Markdown being quite positive, and with Quarto^[Quarto is a multi-language, next-generation version of R Markdown from Posit and includes dozens of new features and capabilities while at the same being able to render most existing Rmd files without modification. Quarto was recently released, has evolved rapidly, and is now quite stable (Version 1.0 was released publicly July 28 2022 - see <a href="https://posit.co/blog/announcing-quarto-a-new-scientific-and-technical-publishing-system">Quarto Announcement</a>.] broadening its embrace far beyond RStudio and R (and re-branding as Posit), it became clear that clinging to R blogdown was a recipe for pain that I didn't need, and that Quarto was one obvious way forward (R blogdown uses R Markdown, which is almost the same as Quarto Markdown).

So, after the jet lag had passed while visiting a co-author at the University of Pretoria, I decided to devote part of a morning to migrating my old R blogdown code to the Quarto blogging framework and to host it directly on GitHub Pages (a free site hosting service).

The migration was very straightforward, and in less than one hour I was up and running with the migrated site (probably closer to 1/2 an hour of work was required, at most). So far I am very happy with the result, and there seems to be far less to maintain than was the case when using R blogdown (at least this is my recollection). Hopefully this platform turns out to be more "future-proofed" than its predecessor! 

Only time will tell if this newly adopted framework is more resilient than its predecessor. At minimum, a small time investment has resurrected my historical blog posts and allowed me to effortlessly create at least one new post, thanks to the efforts of the developers at Posit (formerly RStudio). I would be more than happy to discuss additional details with you if you wish (shoot me an email!). See <a href="https://quarto.org/docs/get-started">quarto.org/docs/get-started</a> to get started with Quarto and <a href="https://quarto.org/docs/websites/website-blog">quarto.org/docs/websites/website-blog</a> for information on using Quarto to create a blog.
